spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

logging:
  level:
#    org.hibernate.SQL: debug
#    org.hivernate.type: trace
    org.springframework.orm.jpa: DEBUG

server:
  servlet:
    context-path: /api

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

aws:
  sns:
    accessKey: ENC(KfNNrA8GqM4B9XoqWbV0ZICp3xD5bpD/gqAcK7LvE9A=)
    secretKey: ENC(/kTt6VuTkcxL0HYPAJr5eP+QDmJk3pRy3CoO7E+RQvFXB3UgFYm8qdlVjJ0VriP6J20IL2be/Ls=)