spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.cnplc5iklrxo.ap-northeast-2.rds.amazonaws.com:3306/barking-cat?autoReconnect=true&useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

logging:
  level:
#    org.hibernate.SQL: debug
#    org.hivernate.type: trace
    org.springframework.orm.jpa: DEBUG

server:
  servlet:
    context-path: /api
