import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Script from 'next/script';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>야옹아 멍멍해봐</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script
        strategy="beforeInteractive"
        id="kakao-init"
        src="https://developers.kakao.com/sdk/js/kakao.min.js"
      ></Script>

      <Script id="init">
        {`Kakao.init("${process.env.NEXT_PUBLIC_KAKAO_KEY}");`}
      </Script>
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
