import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>야옹아 멍멍해봐</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          src="https://developers.kakao.com/sdk/js/kakao.min.js"
        ></script>
        <script>Kakao.init("2a0e79ce67d1fb9dd713ca1a8b493338")</script>
      </Head>
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
