import { PostCardItem } from 'types/api';
import PostCards from '@/components/PostCards';
import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import { BoardResponse } from 'types/api';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const [data, setData] = useState<PostCardItem[]>([]);

  const router = useRouter();

  async function fetch() {
    const { data } = await axios.get<BoardResponse>('/api/board');
    setData(
      data.content.map((e) => ({
        id: e.boardId,
        createdDate: '2021-10-02',
        dueDate: e.dueDate,
        title: e.title,
        tags: e.tags,
        img: 'img',
        likes: 1,
        comments: 2,
        reads: 3,
      }))
    );
  }

  useEffect(() => {
    fetch();
  }, []);

  function handleSignInClick() {
    router.push('/signin');
  }
  function handleSignUpClick() {
    router.push('/signup');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>야옹아 멍멍해봐</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handleSignInClick}>로그인</button>
        <button onClick={handleSignUpClick}>회원가입</button>
        <PostCards items={data} />
      </main>
    </div>
  );
};

export default Home;
