import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';

const SignIn: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>야옹아 멍멍해봐</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>SignUp</main>
    </div>
  );
};

export default SignIn;
