name: Front
on:
  push:
    branches: ['front']

env:
  IMAGE: lifeboat/barking-cat-web

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Login to Docker
        run: |
          echo ${{ secrets.FRONT_DOCKER_PW }} | \
          docker login \
          -u ${{ secrets.FRONT_DOCKER_ID }} \
          --password-stdin
      - name: Create env file
        run: |
          echo NEXT_PUBLIC_API_URL=${{ secrets.API_URL }} &> .env
          echo NEXT_PUBLIC_KAKAO_KEY=${{ secrets.KAKAO_KEY }} >> .env
      - name: Pull Image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build Image
        run: |
          echo `ls`
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            "."
      - name: Push Image
        run: |
          docker push ${{ env.IMAGE }}:latest

  deploy:
    name: Deploy to EC2
    runs-on: [self-hosted]
    needs: [build]
    steps:
      - name: Login to Docker
        run: |
          echo ${{ secrets.FRONT_DOCKER_PW }} | \
          docker login \
          -u ${{ secrets.FRONT_DOCKER_ID }} \
          --password-stdin
      - name: Docker run
        run: |
          docker stop barking-cat-web && docker rm barking-cat-web || true
          docker rmi -f ${{ env.IMAGE }}:latest || true
          docker run -d -p 3000:3000 --name barking-cat-web lifeboat/barking-cat-web:latest
